# removed trigger for changes in main branch

pr: none
trigger: none

resources:
  repositories:
    - repository: apk
      type: github
      name: renuka-fernando/apk
      ref: choreo

  pipelines:
    - pipeline: apk-CI
      source: apk-CI
      project: control-plane-components
      trigger:
        branches:
          - choreo

variables:
  - group: cp-components-choreo-release-secrets
  - name: CONTAINER_REGISTRY
    value: choreocontrolplane.azurecr.io
  #  - name: PDP_CONTAINER_REGISTRY
  #    value: choreoprivateacr.azurecr.io
  - name: ADAPTER_REPOSITORY
    value: choreoipaas/choreo-apk-adapter
  - name: COMMON_CONTROLLER_REPOSITORY
    value: choreoipaas/choreo-apk-common-controller
  - name: CONFIG_DEPLOYER
    value: choreoipaas/choreo-apk-config-deployer
  - name: ENFORCER_REPOSITORY
    value: choreoipaas/choreo-apk-enforcer
  - name: RATE_LIMITER_REPOSITORY
    value: choreoipaas/choreo-apk-rate-limiter
  - name: ROUTER_REPOSITORY
    value: choreoipaas/choreo-apk-router
  - name: ADAPTER_VERSION
    value: ''
  - name: COMMON_CONTROLLER_VERSION
    value: ''
  - name: CONFIG_DEPLOYER_VERSION
    value: ''
  - name: ENFORCER_VERSION
    value: ''
  - name: RATE_LIMITER_VERSION
    value: ''
  - name: ROUTER_VERSION
    value: ''
  - name: GIT_COMMIT_ID
    value: ''
